#	Assignment: CS3516 Assignment 1
#	Author: Alexander MacDonald
#	Date: 11/8/2022

all: server client

server: server-final.c
	gcc server-final.c -o server.o
		
client: client-final.c
	gcc client-final.c -o client.o
	
clean:
	rm *.o *.txt
